#!/bin/bash

NAME=crackerjack
EMAIL=watjen.fire@gmail.com
PROJECT=workout_manager

docker run -it -e NAME=$NAME -e EMAIL=$EMAIL -e PROJECT=$PROJECT --mount type=bind,source=$PWD,target=/$PROJECT --workdir /$PROJECT nesscool/basecpp:base
