#!/bin/bash

NAME=crackerjack
EMAIL=watjen.fire@gmail.com
PROJECT=basecpp

docker run -it -e NAME=$NAME -e EMAIL=$EMAIL -e PROJECT=$PROJECT --mount type=bind,source=/home/swatjen/c++/$PROJECT,target=/$PROJECT --workdir /$PROJECT basecpp:gcm
